### ISSUE TITLE
Pest 2.0 breaks result parsing

### ISSUE THREAD

**Issue by V13Axel** [theutz/neotest-pest#5]
It looks like Pest 2.0 requires phpunit >10, which has broken test result parsing. Not sure if this is something there's an easy solution to, that I am just perhaps overlooking? But since I could reproduce it on this very repo's examples, I thought I'd at least bring it up in case this project is not as abandoned as it seems :sweat_smile: 

You can reproduce it by cloning this very repository, updating Pest to 2.0, then doing a `lua require('neotest').run.run()` on any test, where you'll see all tests, pass or fail, are being (wrongly) parsed as failing.

I spent a few hours last night trying to get familiar with neotest by looking through the `neotest-pest` and `neotest-phpunit`, but so far I can't quite figure out _exactly_ where the parsing breaks down - but what I have done so far is compare the output of `--log-junit` between the two. 

Here's phpunit 9:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="/path/to/repo/tests/Unit/ExampleTest.php" tests="1" assertions="1" errors="0" warnings="0" failures="0" skipped="0" time="0.002297">
    <testsuite name="P\Tests\Unit\ExampleTest" file="/path/to/repo/tests/Unit/ExampleTest.php" tests="1" assertions="1" errors="0" warnings="0" failures="0" skipped="0" time="0.002297">
      <testcase name="true is true" class="Tests\Unit\ExampleTest" classname="Tests.Unit.ExampleTest" file="/path/to/repo/tests/Unit/ExampleTest.php" assertions="1" time="0.002297"/>
    </testsuite>
  </testsuite>
</testsuites>
```

And here's phpunit 10:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="Tests\Unit\ExampleTest" file="tests/Unit/ExampleTest.php" tests="1" assertions="1" errors="0" failures="0" skipped="0" time="0.004544">
    <testcase name="true is true" file="tests/Unit/ExampleTest.php::true is true" class="Tests\Unit\ExampleTest" classname="Tests.Unit.ExampleTest" assertions="1" time="0.004544"/>
  </testsuite>
</testsuites>
```

I'm going to continue digging into it, but I'd love some input from anyone who knows neotest better than I do (which is _barely_)! :smile:

**Comment by theutz** [comment]
Hey there! Thanks for contributing this and for the comprehensive context. Unfortunately, my dev work in the last few months has taken me away from doing Laravel stuff (hopefully only for a short while). As such, I haven't had as much need for this plugin and haven't been using it.

That said, when I move back to Laravel-land, I'll probably make a priority of fixing this up. Until then, I'd be happy to welcome any contributions to fix this!

**Comment by V13Axel** [comment]
I actually spent a few days grokking through how the codebase works and reading through Neotest's documentation, fixed the problem, and reworked a few other things in my own fork: https://github.com/V13Axel/neotest-pest

While I could always submit my changes as a PR, I'd actually be glad to take over as the primary maintainer of `neotest-pest` if that would be more helpful to you! Laravel is my bread-and-butter, so I've got plenty imperative to keep it supported. So if you're otherwise occupied, I'll even gladly submit a PR to the Pest website putting forth the URL to my fork.

**Comment by theutz** [comment]
I’d be more than happy to let you take up the mantle! Let me know if there’s anything I need to do to help.

**Comment by V13Axel** [comment]
With ^ that @theutz it looks like the weight's off your shoulders =]

Any chance you can add a note to the readme, pointing folks my direction?

**Comment by theutz** [comment]
Sure thing! It's done. I'll archive the repo now, too. Thanks for your work on this!
